# Generated by Django 5.0.6 on 2024-07-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
